title: Your Lab Name
description: Welcome to the official wiki of Our Research Group

# Use Just the Docs via remote_theme
remote_theme: just-the-docs/just-the-docs

# Enable search bar
search_enabled: true

# Navigation order (optional)
nav_order: 1
